### ISSUE TITLE
Can't deploy, TLS ERROR TLS certificate not implemented

### ISSUE THREAD

**Issue by koemadf** [DesktopECHO/pideploy#2]
Hello, I'm trying to install pi-hole on a old android (lineage os 7.1 with supersu) ,I'm having this error when I press New deploy :
![P_20231207_183510](https://github.com/DesktopECHO/pideploy/assets/102315546/198c95c2-62f1-485e-815d-0feac0c25b39)

**Comment by DesktopECHO** [comment]
If you can, try a different WiFi network.  

You can also download the file using the web browser installed on the device.  When the image is downloaded, open Pi Deploy and tap Properties.  Change the _Source path_ from:

`https://github.com/DesktopECHO/Pi-hole-for-Android/releases/latest/download/raspbian.tgz`

..to the location of the downloaded file (exact path may vary by device):

`/sdcard/Download/raspbian.tgz `

**Comment by koemadf** [comment]
> If you can, try a different WiFi network.
> 
> You can also download the file using the web browser installed on the device. When the image is downloaded, open Pi Deploy and tap Properties. Change the _Source path_ from:
> 
> `https://github.com/DesktopECHO/Pi-hole-for-Android/releases/latest/download/raspbian.tgz`
> 
> ..to the location of the downloaded file (exact path may vary by device):
> 
> `/sdcard/Download/raspbian.tgz `

It Worked.!!
![9dsf86d8f76](https://github.com/DesktopECHO/pideploy/assets/102315546/ad1b1cd2-33f0-4681-84c6-9f18a73ed2c2)


Thank You very much.

**Comment by DesktopECHO** [comment]
Great to hear!  

FYI, for the latest news, updates, and disk image releases, visit the [Pi-hole for Android](https://github.com/DesktopECHO/Pi-hole-for-Android) repository.  

You also may want to redeploy your image; today I released new [32 and 64-bit disk images for Pi Deploy](https://github.com/DesktopECHO/Pi-hole-for-Android/releases/latest).  
It comes with Debian 12 and installers for Pi-hole, NextCloud, and PIXEL desktop environment.
