### ISSUE TITLE
android-rasbian ... chroot can't execute '/bin/su' No such file or directory fail

### ISSUE THREAD

**Issue by weisserwerwolf89** [DesktopECHO/pideploy#3]
Hello everyone,

First of all, thank you for giving old cell phones a new life.

I wanted to use a rooted Samsung Galaxy S4 with Android 5 for your app. Installation did not work. So I installed BusyBox and changed the "Path variable" to /system/xbin, just like it worked with Linux Deploy. In addition, the download did not work, so I downloaded the file "raspbian.tgz" manually and changed the path under "Proberties:Rasbian " and I changed the username to root.

If I now click on "new Deployment", the installation seems to run smoothly. But when I mount the counainer I get the error message:

::Starting init/sysv:

android-rasbian ... chroot can't execute '/bin/su' No such file or directory fail

and many more of the same error messages with different file names. 

Do you have a suggestion for a solution?

Translated with DeepL.com (free version)

**Comment by DesktopECHO** [comment]
Hello, 

For a device that old, you need to use the 32-bit image:

[https://github.com/DesktopECHO/Pi-hole-for-Android/releases/latest/download/raspbian32.tgz](https://github.com/DesktopECHO/Pi-hole-for-Android/releases/latest/download/raspbian32.tgz)

**Comment by weisserwerwolf89** [comment]
Thank you. :-)
